### ISSUE TITLE
Time displayed in system incorrect - rounding issue

### ISSUE THREAD

**Issue by cmaneu** [johnpapa/vscode-read-time#10]
Sometimes, I don't get the same timing on the Status bar and on the tooltip when hoovering. While showing the same document, the Status bar indicates 2 minutes
![image](https://user-images.githubusercontent.com/790974/55688148-bab54b80-5975-11e9-8a12-96a220588ccd.png)
But when hoovering I see 3 minutes
![image](https://user-images.githubusercontent.com/790974/55688153-c4d74a00-5975-11e9-8dce-41448b5323f2.png)

Maybe a rounding/truncating issue?

**Comment by johnpapa** [comment]
ah, good catch.

the package i am using must be doing something different the status bar item is using `Math.round(readingTimeData.minutes).toString()` while the tooltip uses `readingTimeData.text`.

The underlying package uses `Math.ceil(minutes.toFixed(2))` to set the `text` (which is what i use for tooltip).


I just changed the logic to use `Math.round` for both the status bar and the tooltip as of v 0.1.9
