### ISSUE TITLE
Unable to install extension

### ISSUE THREAD

**Issue by cmaneu** [johnpapa/vscode-read-time#8]
# Unable to install extension

## Version Information

- Windows 10 Pro - public ring
- VS Code 1.30.2 commit 61122f88f
- Read Time version 0.1.8

## Repro steps

1. Go to [https://marketplace.visualstudio.com/items?itemName=johnpapa.read-time](https://marketplace.visualstudio.com/items?itemName=johnpapa.read-time)
2. Click on **Install**, and then on **Continue**
3. VS Code is launching, opening the _Read time_ extension page. Click on **Install**

Expected result: the action is installing / installed
Actual result: Message `Failed to install johnpapa.read-time.` shown as a notification. Action of Downloading manually the extension appears.

## The log given by the failure

There is no logs :)

**Comment by cmaneu** [comment]
Just upgraded VS Code to 1.33 and is working !

**Comment by johnpapa** [comment]
Yes - there is a requirement of 1.31

```
    "vscode": "^1.31.0"

```

**Comment by cmaneu** [comment]
Hmm, so VS Code is not warning you if requirements are not met? Seems like a bug for VS Code then :)

**Comment by johnpapa** [comment]
perhaps.

or just keep updated :)
